global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.1.10.52:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
